name: sundays
display_name: Sundays
version: 1.0.0
theme_key: 9b876391e56837563cdb276233ae83b5
author:
  name: "Anvanto Team"
  email: "applynovation@gmail.com"
  url: "http://anvanto.com"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column
      
dependencies:
  modules:
    - an_theme
    - anproductextratabs
    - anproductvideos
    - anscrolltop
    - an_brandslider
    - anthemeblocks 

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
#  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#  js:
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
   to_enable:
     - ps_linklist
     - anproductextratabs
     - anproductvideos
     - anscrolltop
     - an_theme
     - anthemeblocks
     - an_brandslider
     
   to_disable:
    - blockreassurance
    - ps_imageslider
  hooks:
    modules_to_hook:
      displayNav1:
        - ps_contactinfo
        - anthemeblocks
        - ps_languageselector
        - ps_currencyselector
      displayNav2:
        - ps_customersignin
        - ps_shoppingcart
        - anthemeblocks
      displayTop:
        - ps_mainmenu
        - ps_searchbar
        - anthemeblocks
      displayHome:
        - ps_featuredproducts
        - anthemeblocks
        - an_brandslider        
      displayFooterBefore:
        - anthemeblocks
      displayFooter:
        - ps_emailsubscription 
        - ps_linklist
        - ps_customeraccountlinks
        - anscrolltop  
        - anthemeblocks  
      displayAdminProductsExtra:
        - ~
        - anproductextratabs
        - anproductvideos           
      displayFooterAfter:
        - ps_contactinfo
        - ps_socialfollow
        - anthemeblocks
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
        - anthemeblocks
      displaySearch:
        - ps_searchbar
        - anthemeblocks
      displayProductButtons:
        - ~
        - anthemeblocks  
      displayReassurance:
        - anthemeblocks
      displayOrderConfirmation2:
        - ps_featuredproducts
        - anthemeblocks        
      displayCrossSellingShoppingCart:
        - ps_featuredproducts
        - anthemeblocks 
      displayProductExtraContent:
        - anproductextratabs
        - anproductvideos
        - anthemeblocks
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - anthemeblocks
      displayBeforeBodyClosingTag:
        - ~
        - anthemeblocks
      displayCartExtraProductActions:
        - ~
        - anthemeblocks
      displayCopyrightContainer:
        - ~
        - anthemeblocks
      displayCustomerAccount:
        - ~
        - anthemeblocks
      displayCustomerLoginFormAfter:
        - ~
        - anthemeblocks
      displayFooterProduct:
        - ~
        - anthemeblocks
      displayHomeAfter:
        - ~
        - anthemeblocks
      displayHomeBefore:
        - ~
        - anthemeblocks
      displayLeftColumnProduct:
        - ~
        - anthemeblocks
      displayMyAccountBlock:
        - ~
        - anthemeblocks
      displayNav:
        - ~
        - anthemeblocks
      displayNavFullWidth:
        - ~
        - anthemeblocks
      displayOrderConfirmation:
        - ~
        - anthemeblocks
      displayPaymentByBinaries:
        - ~      
        - anthemeblocks
      displayPaymentTop:
        - ~      
        - anthemeblocks
      displayRightColumn:
        - ~      
        - anthemeblocks
      displayRightColumnProduct:
        - ~      
        - anthemeblocks
      displayShoppingCart:
        - ~
        - anthemeblocks
      displayShoppingCartFooter:
        - ~
        - anthemeblocks
      displaySliderContainerWidth:
        - ~
        - anthemeblocks
      displaySliderFullWidth:
        - ~
        - anthemeblocks
      displayTopColumn:
        - ~
        - anthemeblocks
      displayBackOfficeHeader:
        - ~
        - anthemeblocks
        - anproductvideos

  image_types:
    cart_default:
      width: 148
      height: 148
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
    brand_default:
      width: 135
      height: 30
      scope: [manufacturers]

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column
